### ISSUE TITLE
Question: Shipping Terraform plugin with Vault

### ISSUE THREAD

**Issue by husunal** [hashicorp/vault-plugin-secrets-terraform#4]
Great work, thanks! 

Is there a plan to ship this plugin as part of Vault as a built-in plugin?

**Comment by catsby** [comment]
Hello there @husunal ! Yes, we plan to bundle this into an upcoming release of Vault, see https://github.com/hashicorp/vault/pull/10931 . After that gets merged, the next release of Vault will include this plugin. 

I'm going to close this for now, thanks!
